---
version: "3"
services: 
  postgredb-market:
    image: "postgres:9.6.12"
    container_name: "postgredb-market"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5433:5432"
    volumes:
      - ./postgredb:/docker-entrypoint-initdb.d/